---
image:
    file: .gitpod.Dockerfile

# Commands that will run on workspace start 
tasks: 
    - name: Build & Deploy
      init: cargo build -r
      command: redis-server --port 8082 & ./target/release/websurfx

# vscode IDE setup
vscode: 
   extensions: 
    - vadimcn.vscode-lldb
    - cschleiden.vscode-github-actions
    - rust-lang.rust-analyzer
    - bungcip.better-toml
    - serayuzgur.crates
    - usernamehw.errorlens
    - DavidAnson.vscode-markdownlint
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - dbaeumer.vscode-eslint
    - evgeniypeshkov.syntax-highlighter
    - ms-azuretools.vscode-docker
    - Catppuccin.catppuccin-vsc
    - PKief.material-icon-theme
    - oderwat.indent-rainbow
    - formulahendry.auto-rename-tag
    - swellaby.vscode-rust-test-adapter
    - belfz.search-crates-io
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
    - eamodio.gitlens
github: 
   prebuilds: 
      master: true 
      branches: true 
      pullRequests: true 
      pullRequestsFromForks: true 
      addCheck: true 
      addComment: false
      addBadge: true
