name: Rust

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "rolling" 

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
    - name: Cache Rust compilation
      uses: metalbear-co/sccache-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Optional, default is `sccache-`
        cache-from: sccache-${{ runner.os }}-
        # Optional, default is `sccache-latest`
        cache-to: sccache-${{ runner.os }}-${{ github.sha }}
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
